.PHONY: all clean

all: \
    0 \
    1 \
    2 \
    3 \
    4 \
    5

0: src/0.c
    $(CC) -o bin/0 src/0.c

1: src/1.c
    $(CC) -o bin/1 src/1.c

2: src/2.c
    $(CC) -o bin/2 src/2.c

3: src/3.c
    $(CC) -o bin/3 src/3.c

4: src/4.c
    $(CC) -o bin/4 src/4.c

5: src/5.c
    $(CC) -o bin/5 src/5.c

clean:
    rm -f bin/0
    rm -f bin/1
    rm -f bin/2
    rm -f bin/3
    rm -f bin/4
    rm -f bin/5
